### ISSUE TITLE
Some Rails integration tests fail with rack 3.1

### ISSUE THREAD

**Issue by Fjan** [rack/rack#2212]
After upgrading rack from 3.0.11 to 3.1.3 any reference to `request.raw_post` in our Rails code base fails during integration tests. However the code works fine, also in controller and system tests. It looks like the header 'rack.input' no longer gets set during integration tests. Should I report this issue to rails or is this an issue with rack?

```
`NoMethodError: undefined method `read' for nil
           /ruby-3.3.1/gems/actionpack-7.1.3.4/lib/action_dispatch/http/request.rb:472:in `read_body_stream'
```

**Comment by ioquatix** [comment]
It's a bug in Rails. `rack.input` is now optional and won't be set if there isn't any input.

**Comment by Fjan** [comment]
Thanks, I'll report  it there
