### ISSUE TITLE
session_abstract_id.rb `stringify_keys' breaks when using devise, rspec and rails-controller-testing

### ISSUE THREAD

**Issue by StinkySteve** [rack/rack#1532]
I'm not sure it should be reported here but bumping rack seems to have caused it. 

Everything works fine with rack 2.0.8.

Rack 2.1.2
```
NoMethodError:
   undefined method `transform_keys' for [[6267], "$2a$04$IauExC5wwLatXc6fvAml.O"]:Array
   Did you mean?  to_h
 # /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:204:in `stringify_keys'
 # /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:140:in `update'
 # /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/template_assertions.rb:61:in `process'
 # /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:35:in `block in process'
 # /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:102:in `catch'
 # /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:102:in `_catch_warden'
 # /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:35:in `process'
 # /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13:in `block (2 levels) in <module:Integration>'
 # ./spec/controllers/propositions_controller_spec.rb:165:in `block (3 levels) in <top (required)>'
```

Rack 2.1.0
```
NoMethodError:
  undefined method `transform_keys' for [[6267], "$2a$04$IauExC5wwLatXc6fvAml.O"]:Array
  Did you mean?  transpose
# /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/rack-2.1.0/lib/rack/session/abstract/id.rb:212:in `stringify_keys'
# /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/rack-2.1.0/lib/rack/session/abstract/id.rb:148:in `update'
# /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/template_assertions.rb:61:in `process'
# /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:35:in `block in process'
# /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:102:in `catch'
# /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:102:in `_catch_warden'
# /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:35:in `process'
# /Users/me/.rvm/gems/ruby-2.6.1@adfl/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13:in `block (2 levels) in <module:Integration>'
# ./spec/controllers/propositions_controller_spec.rb:83:in `block (5 levels) in <top (required)>'
```

**Comment by jeremyevans** [comment]
`transform_keys` in 2.1.2 is called on the result of `to_hash` (https://github.com/rack/rack/blob/2.1.2/lib/rack/session/abstract/id.rb#L204).  Do you have a rack.session object that responds to `to_hash` but does not return a hash?  That violates rack's SPEC.

**Comment by StinkySteve** [comment]
I might have to clarify that it breaks in rspec only! 

Its just an array. I agree that this seems kind of odd but it used to work fine with 2.0.8. I agree that it seems like undocumented behaviour. 
I guess the `other` argument comes from warden or rails_controller_testing. I'll look into it and close this issue on my way out.

**Comment by jeremyevans** [comment]
As this doesn't appear to be a bug, I'm going to close this now.  If after investigation you think this is a bug in rack, please post details.
